name: Plan and Apply Called Workflow

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: true
        type: string
      github_environment:
        required: true
        type: string
      service_account:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      terraform_plan_args:
        required: false
        type: string
      terraform_state_bucket:
        required: true
        type: string
      terraform_workspace:
        required: true
        type: string
      working_directory:
        required: false
        type: string
        default: .
      workload_identity_provider:
        required: true
        type: string

    secrets:
      gpg_passphrase:
        required: true

      # Uncomment if you have private modules
      # ssh_key:
      #   required: true

      terraform_plan_secret_args:
        required: false

# If you use private modules you'll need this env variable to use
# the same ssh-agent socket value across all jobs & steps.
# env:
#  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

permissions:
  # The job or workflow run requires a permissions setting with id-token: write.
  # You won't be able to request the OIDC JWT ID token if the permissions setting
  # for id-token is set to read or none.

  id-token: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ inputs.checkout_ref }}

      # Google Cloud Platform - Authenticate to Google Cloud
      # https://github.com/marketplace/actions/authenticate-to-google-cloud

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v1.0.0
        with:
          create_credentials_file: true
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      # GitHub - Setup SSH for Module Access
      # Uncomment if you have private modules

      # - name: Step ssh for private module access
      #   run: |
      #     ssh-agent -a $SSH_AUTH_SOCK
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ssh_key }}" | tr -d '\r' | ssh-add -
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      # # Provider Plugin Cache
      # # https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache

      # - name: Config Terraform plugin cache
      #   run: |
      #     echo 'plugin_cache_dir="${{ inputs.working_directory }}/.terraform.d/plugin-cache"' > ~/.terraformrc
      #     mkdir -p ${{ inputs.working_directory }}/.terraform.d/plugin-cache

      # GitHub - Cache
      # https://github.com/marketplace/actions/cache

      - name: Setup Cache
        uses: actions/cache@v3.2.3
        with:
          path: |
            ${{ inputs.working_directory }}/.terraform/providers
            ${{ inputs.working_directory }}/.terraform/modules
            ${{ inputs.working_directory }}/plan.out.gpg
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

      # HashiCorp - Setup Terraform
      # https://github.com/marketplace/actions/hashicorp-setup-terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Initialize
        run: terraform init -backend-config="bucket=${{ inputs.terraform_state_bucket }}"

      - name: Terraform Workspace
        run: >-
          terraform workspace select ${{ inputs.terraform_workspace }} ||
          terraform workspace new ${{ inputs.terraform_workspace }}

      - name: Terraform Format
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -input=false -out=plan.out ${{ inputs.terraform_plan_args}} ${{ secrets.terraform_plan_secret_args }}

      # Encrypt - Terraform plan.out

      # If your plan includes any sort of sensitive data, even if obscured in Terraform's terminal output,
      # it will be saved in cleartext in the plan file. You should therefore treat any saved plan files as
      # potentially-sensitive artifacts.

      - name: Encrypt
        if: steps.plan.outputs.exitcode == 2
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.gpg_passphrase }} --symmetric --cipher-algo AES256 plan.out

    outputs:
      planExitcode: ${{ steps.plan.outputs.exitcode }}

  apply:
    name: Terraform Apply
    needs: plan
    if: needs.plan.outputs.planExitcode == 2
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github_environment }}

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ inputs.checkout_ref }}

      # Google Cloud Platform - Authenticate to Google Cloud
      # https://github.com/marketplace/actions/authenticate-to-google-cloud

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v1.0.0
        with:
          create_credentials_file: true
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      # GitHub - Setup SSH for Module Access
      # Uncomment if you have private modules

      # - name: Step ssh for private module access
      #   run: |
      #     ssh-agent -a $SSH_AUTH_SOCK
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ssh_key }}" | tr -d '\r' | ssh-add -
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      # GitHub - Cache
      # https://github.com/marketplace/actions/cache

      - name: Setup Cache
        uses: actions/cache@v3.2.3
        with:
          path: |
            ${{ inputs.working_directory }}/.terraform/providers
            ${{ inputs.working_directory }}/.terraform/modules
            ${{ inputs.working_directory }}/plan.out.gpg
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

      # Decrypt - Terraform plan.out

      - name: Decrypt
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.gpg_passphrase }} --output plan.out plan.out.gpg

      # HashiCorp - Setup Terraform
      # https://github.com/marketplace/actions/hashicorp-setup-terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Initialize
        run: terraform init -backend-config="bucket=${{ inputs.terraform_state_bucket }}"

      - name: Terraform Workspace
        run: terraform workspace select ${{ inputs.terraform_workspace }}

      - name: Terraform Apply
        run: terraform apply plan.out
