name: Kitchen-Terraform

on:
  workflow_call:
    inputs:
      service_account:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string

jobs:
  kitchen-terraform:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest

    steps:
      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Run step checkout
        uses: actions/checkout@v3.1.0


      # Google Cloud Platform - Authenticate to Google Cloud
      # https://github.com/marketplace/actions/authenticate-to-google-cloud

      - name: Run step authenticate-to-google-cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          create_credentials_file: true
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      # Kitchen Terraform
      # https://github.com/marketplace/actions/kitchen-terraform-github-action

      - name: Run step kitchen converge
        uses: osinfra-io/github-kitchen-terraform-action@v1.2.1
        with:
          kitchen-command: converge

      - name: Run step kitchen verify
        uses: osinfra-io/github-kitchen-terraform-action@v1.2.1
        with:
          kitchen-command: verify

      - name: Run step kitchen destroy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: osinfra-io/github-kitchen-terraform-action@v1.2.1
        with:
          kitchen-command: destroy
