name: Kitchen-Terraform

on:
  workflow_call:
    secrets:
      service_account:
        required: true
      workload_identity_provider:
        required: true

jobs:
  kitchen-terraform:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest

    steps:
      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@v3.5.0

      # Google Cloud Platform - Authenticate to Google Cloud
      # https://github.com/marketplace/actions/authenticate-to-google-cloud

      - name: Authenticate
        uses: google-github-actions/auth@v1.0.0
        with:
          create_credentials_file: true
          service_account: ${{ secrets.service_account }}
          workload_identity_provider: ${{ secrets.workload_identity_provider }}

      # Kitchen Terraform
      # https://github.com/marketplace/actions/kitchen-terraform-github-action

      - name: Converge
        uses: osinfra-io/github-kitchen-terraform-action@v1.3.1
        with:
          kitchen-command: converge

      - name: Verify
        uses: osinfra-io/github-kitchen-terraform-action@v1.3.1
        with:
          kitchen-command: verify

      - name: Destroy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: osinfra-io/github-kitchen-terraform-action@v1.3.1
        with:
          kitchen-command: destroy
