name: Kitchen-Terraform

on:
  workflow_call:
    inputs:
      service_account:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string
    secrets:
      billing_account:
        required: false
      datadog_api_key:
        required: false
      datadog_app_key:
        required: false

jobs:
  kitchen_terraform:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest
    env:
      BILLING_ACCOUNT: ${{ secrets.billing_account }}
      DATADOG_API_KEY: ${{ secrets.datadog_api_key }}
      DATADOG_APP_KEY: ${{ secrets.datadog_app_key }}

    steps:

      # Uncomment to enable GitHub Security Lab Action Permissions Monitor

      # - name: Actions permissions monitor
      #   uses: GitHubSecurityLab/actions-permissions/monitor@v1.0.0

      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Google Cloud Platform - Authenticate to Google Cloud
      # https://github.com/marketplace/actions/authenticate-to-google-cloud

      - name: Authenticate
        uses: google-github-actions/auth@v1.1.1
        with:
          create_credentials_file: true
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      # Kitchen Terraform
      # https://github.com/marketplace/actions/kitchen-terraform-github-action

      - name: Converge
        uses: osinfra-io/github-kitchen-terraform-action@v2.2.0
        with:
          kitchen-command: converge

      # No support for WIF: https://github.com/inspec/inspec-gcp/issues/437

      # - name: Verify
      #   uses: osinfra-io/github-kitchen-terraform-action@v2.2.0
      #   with:
      #     kitchen-command: verify

      - name: Destroy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: osinfra-io/github-kitchen-terraform-action@v2.2.0
        with:
          kitchen-command: destroy
