name: Module Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    if: github.actor != 'dependabot[bot]'
    with:
      service_account: plt-lz-testing-github@plt-lz-terraform-tf00-sb.iam.gserviceaccount.com
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      working_directory: tests/test
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
