name: Module Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    if: github.actor != 'dependabot[bot]'
    with:
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      working_directory: tests/test
