name: Non-Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Main
    uses: ./.github/workflows/plan-and-apply.yml
    if: github.actor != 'osinfra-sa'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Non-Production: Main"
      service_account: plt-lz-testing-github@plt-lz-backend-tfa3-nonprod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/plt-lz-backend-tfa3-nonprod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=tfvars/non-production.tfvars
      opentofu_state_bucket: plt-lz-testing-ecf2-nonprod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-non-production
      working_directory: tests/plan-and-apply
      workload_identity_provider: projects/992372365053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
