name: Production

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Non-Production
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Main
    uses: ./.github/workflows/plan-and-apply.yml
    if: github.event.workflow_run.conclusion == 'success'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production: Main"
      service_account: plt-lz-testing-github@plt-lz-backend-tf5f-prod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/plt-lz-backend-tf5f-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=tfvars/production.tfvars
      opentofu_state_bucket: plt-lz-testing-d3c2-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-production
      working_directory: tests/plan-and-apply
      workload_identity_provider: projects/134040294660/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
