name: Sandbox Destroy

on:
  workflow_dispatch:

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  id-token: write
  contents: read

jobs:
  global_infra:
    name: Global
    uses: ./.github/workflows/plan-and-apply.yml
    with:
      checkout_ref: ${{ github.ref }}
      environment: sandbox
      github_environment: "Sandbox Infrastructure: Global"
      service_account: plt-lz-testing-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/sandbox.tfvars
      terraform_state_bucket: plt-lz-testing-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: global-sandbox
      working_directory: tests
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
