name: Sandbox Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Main
    uses: ./.github/workflows/plan-and-apply.yml
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox: Main"
      service_account: plt-lz-testing-github@plt-lz-terraform-tf00-sb.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/plt-lz-backend-tf69-sb/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -destroy -var-file=tfvars/sandbox.tfvars
      opentofu_state_bucket: plt-lz-testing-4312-sb
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-sandbox
      working_directory: tests/plan-and-apply
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
