name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:

  # GITHUB_TOKEN permissions can only be the same or more restrictive in nested workflows.

  # The job or workflow run requires a permissions setting with id-token: write.
  # You won't be able to request the OIDC JWT ID token if the permissions setting
  # for id-token is set to read or none.

  id-token: write

jobs:
  global_infra:
    name: "Global"
    uses: ./.github/workflows/gcp-plan-and-apply.yml
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: global-sandbox
      working_directory: test
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
      terraform_state_bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
