name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  id-token: write

jobs:
  global_infra:
    name: "Global"
    uses: ./.github/workflows/plan-and-apply.yml
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: testing-github-actions@shared-terraform-tfaf-sb.iam.gserviceaccount.com
      terraform_state_bucket: shared-terraform-tfaf-sb-testing
      terraform_version: 1.4.2
      terraform_workspace: global-sandbox
      working_directory: test
      workload_identity_provider: projects/536011305726/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      ssh_key: ${{ secrets.IDEXX_RO_SSH_PRIV_KEY }}
