name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: ./.github/workflows/gcp-plan-and-apply.yml
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: testing-github-actions@shared-terraform-tf1e-sb.iam.gserviceaccount.com
      terraform_state_bucket: shared-terraform-tf1e-sb-testing
      terraform_version: 1.3.7
      terraform_workspace: global-sandbox
      working_directory: test
      workload_identity_provider: projects/417072053896/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
