name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: ./.github/workflows/gcp-plan-and-apply.yml
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: ${{ secrets.SERVICE_ACCOUNT }}
      terraform_state_bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
      terraform_version: 1.3.9
      terraform_workspace: global-sandbox
      working_directory: test
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
